import { Category, DriveFile } from '../types';

// Helper to convert Google Drive view links to direct download links
const getDirectLink = (id: string) => `https://drive.google.com/uc?export=download&id=${id}`;

const HAMUWIYA_FILES: DriveFile[] = [
    {
        id: 'pdf-0',
        name: 'الحموية لابن تيمية.pdf',
        type: 'pdf',
        url: getDirectLink('1BfYQQGtAF9Xs1ZxGzeJ17zn8jRjTYYc1'),
    },
    {
        id: 'audio-1',
        name: 'الحموية لابن تيمية ደርስ 1',
        type: 'audio',
        url: getDirectLink('1I9Ujp0wUSPSOLm_kp7z6IST08IEZLE1T'),
    },
    {
        id: 'audio-2',
        name: 'الحموية لابن تيمية ደርስ 2',
        type: 'audio',
        url: getDirectLink('11RScojtVQYSRLZCQ9RIOxJJ496XRSdEV'),
    },
    {
        id: 'audio-3',
        name: 'الحموية لابن تيمية ደርስ 3',
        type: 'audio',
        url: getDirectLink('1ay7Y4eCDbPiV5QY-eF-graeIwrNfAgm8'),
    },
    {
        id: 'audio-5',
        name: 'الحموية لابن تيمية ደርስ 5',
        type: 'audio',
        url: getDirectLink('1p1i8k-6UlOJKBWpld_2LbiND84PL1Dam'),
    },
    {
        id: 'audio-6',
        name: 'الحموية لابن تيمية ደርስ 6',
        type: 'audio',
        url: getDirectLink('1tzEPMMC8bEkUDJ92hBaUnDW3N53Lvi1h'),
    },
    {
        id: 'audio-7',
        name: 'الحموية لابن تيمية ደርስ 7',
        type: 'audio',
        url: getDirectLink('1F8jN8oR3xX1ZvRPZndW1sd7oF77U6br_'),
    },
    {
        id: 'audio-8',
        name: 'الحموية لابن تيمية ደርስ 8',
        type: 'audio',
        url: getDirectLink('1HsDgTGiSgQOP41jsj6ZNLJI3hbeIdPip'),
    },
    {
        id: 'audio-9',
        name: 'الحموية لابن تيمية ደርስ 9',
        type: 'audio',
        url: getDirectLink('1lZ-fl8xN9TXWLqM4sMnYgP5A_YmtEwF7'),
    },
    {
        id: 'audio-10',
        name: 'الحموية لابن تيمية ደርስ 10',
        type: 'audio',
        url: getDirectLink('152KIBLAOituAthORlNbEytp-XEkG2cmy'),
    },
    {
        id: 'audio-11',
        name: 'الحموية لابن تيمية ደርስ 11',
        type: 'audio',
        url: getDirectLink('1k0vlHrXUDZOXbwvX8viwQiydAbwF3z4L'),
    },
    {
        id: 'audio-12',
        name: 'الحموية لابن تيمية ደርስ 12',
        type: 'audio',
        url: getDirectLink('1qNCVV5Ca1HUHEybLY0Ft33zo50k6fU2j'),
    },
    {
        id: 'audio-13',
        name: 'الحموية لابن تيمية ደርስ 13',
        type: 'audio',
        url: getDirectLink('15N7gf7R-mGA6X2Gp7WwO3NA5vk4_AFUs'),
    },
    {
        id: 'audio-14',
        name: 'الحموية لابن تيمية ደርስ 14',
        type: 'audio',
        url: getDirectLink('15N7gf7R-mGA6X2Gp7WwO3NA5vk4_AFUs'),
    },
    {
        id: 'audio-15',
        name: 'الحموية لابن تيمية ደርስ 15',
        type: 'audio',
        url: getDirectLink('1Vw2lT_cthcbZkL_9D4J-vXEPG3iVzpyM'),
    },
    {
        id: 'audio-16',
        name: 'الحموية لابن تيمية ደርስ 16',
        type: 'audio',
        url: getDirectLink('1coK9Xq-0E2f4L959OqV1EPBe9jhvintV'),
    },
    {
        id: 'audio-17',
        name: 'الحموية لابن تيمية ደርስ 17',
        type: 'audio',
        url: getDirectLink('160s7-OhSA8N1z0PQ7zzqaWwWjWI4NzN6'),
    },
    {
        id: 'audio-18',
        name: 'الحموية لابن تيمية ደርስ 18',
        type: 'audio',
        url: getDirectLink('1JTkKe6ewtPqvdys3IPNX90RIU-FtHGzi'),
    },
    {
        id: 'audio-19',
        name: 'الحموية لابن تيمية ደርስ 19',
        type: 'audio',
        url: getDirectLink('1vvOVSSlXguOAa7-47xlhQKMPmWlpG4GT'),
    },
    {
        id: 'audio-20',
        name: 'الحموية لابن تيمية ደርስ 20',
        type: 'audio',
        url: getDirectLink('15ml_c5Rph5d9hwAJVRPajAxbCRzj06Z2'),
    },
];

export const IRSHAD_FILES: DriveFile[] = [
    {
        id: 'irshad-pdf-0',
        name: 'الإرشاد إلى صحيح الاعتقاد.pdf',
        type: 'pdf',
        url: getDirectLink('1vfjS1xNq2qmexBQbyR3J-Jpal8CgT4Ts'),
    },
    {
        id: 'irshad-audio-1',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 1',
        type: 'audio',
        url: getDirectLink('1gsY3p0Vt9WA2mQGkGuJ8DrKFQ07PLshb'),
    },
    {
        id: 'irshad-audio-2',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 2',
        type: 'audio',
        url: getDirectLink('12BjQT4V6d8lrmjCgzMyQarA-QMqVf1Rs'),
    },
    {
        id: 'irshad-audio-3',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 3',
        type: 'audio',
        url: getDirectLink('1_GCPeh9hZ740qB_aEO4KMgTDySURNGAm'),
    },
    {
        id: 'irshad-audio-4',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 4',
        type: 'audio',
        url: getDirectLink('126JulQ7By4DgksyMDiW9p86FDyesugOa'),
    },
    {
        id: 'irshad-audio-5',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 5',
        type: 'audio',
        url: getDirectLink('1RuPFQLvXcubeU-OVVOP1lof4hSdKKJq9'),
    },
    {
        id: 'irshad-audio-6',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 6',
        type: 'audio',
        url: getDirectLink('19WkyHQDBtmgAbBoTloBZnNLyQO5vOB9v'),
    },
    {
        id: 'irshad-audio-7',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 7',
        type: 'audio',
        url: getDirectLink('11a2Ba70rY9A8188tKGBTlgDSfGEvs4pq'),
    },
    {
        id: 'irshad-audio-8',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 8',
        type: 'audio',
        url: getDirectLink('1SXXBkwBpD04qnhF1oUIPz7TTys2YUDqg'),
    },
    {
        id: 'irshad-audio-9',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 9',
        type: 'audio',
        url: getDirectLink('1wGiN1O3ImorqZk6GYDg4MV5u0J9l4UPk'),
    },
    {
        id: 'irshad-audio-10',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 10',
        type: 'audio',
        url: getDirectLink('1qQLr2V9FWi96lbaGXyZ6-bMZ555t2SIj'),
    },
    {
        id: 'irshad-audio-11',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 11',
        type: 'audio',
        url: getDirectLink('1R8fH2Z27HqdhhxwiQq55cXxmdEkR05au'),
    },
    {
        id: 'irshad-audio-12',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 12',
        type: 'audio',
        url: getDirectLink('1Y43fyFFks21A834nQjbsjHcMWiRry6B3'),
    },
    {
        id: 'irshad-audio-13',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 13',
        type: 'audio',
        url: getDirectLink('1EF60ESMffmgEP_Ty6xAh_4W27H-jTriW'),
    },
    {
        id: 'irshad-audio-14',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 14',
        type: 'audio',
        url: getDirectLink('1nH84tJdEtivPSREYBk4zr-Ome6KiUCDE'),
    },
    {
        id: 'irshad-audio-15',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 15',
        type: 'audio',
        url: getDirectLink('1jA1ZuFcnEUsBwoT0ObsqUhHUSthCe6eh'),
    },
    {
        id: 'irshad-audio-16',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 16',
        type: 'audio',
        url: getDirectLink('1OH31DedcAecJ9d4mTv2vOnb9Q5KPDh40'),
    },
    {
        id: 'irshad-audio-17',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 17',
        type: 'audio',
        url: getDirectLink('1JoadJLq0ASqe4AC7U-Jz8ZUVJ4EJ1KTu'),
    },
    {
        id: 'irshad-audio-18',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 18',
        type: 'audio',
        url: getDirectLink('1_-PXVgh5drpXdVqqkTMVmUckWkIiQ_R3'),
    },
    {
        id: 'irshad-audio-19',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 19',
        type: 'audio',
        url: getDirectLink('1g3iliIMrIE_1GsSFz-xCyXbwx709E3qF'),
    },
    {
        id: 'irshad-audio-20',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 20',
        type: 'audio',
        url: getDirectLink('1Ei3qXBrIOgXBXw6JG3_bl79pVSdg12nQ'),
    },
    {
        id: 'irshad-audio-21',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 21',
        type: 'audio',
        url: getDirectLink('1JUe6Un-RLcPTqqDa7h-02HrecdELspSg'),
    },
    {
        id: 'irshad-audio-22',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 22',
        type: 'audio',
        url: getDirectLink('1MRcKiqjSn63rtkXrSYFMMv44-9g43TUb'),
    },
    {
        id: 'irshad-audio-23',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 23',
        type: 'audio',
        url: getDirectLink('1vL5uzAAeMuvCZJUbG5AsrbhNZ5AIGJI8'),
    },
    {
        id: 'irshad-audio-24',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 24',
        type: 'audio',
        url: getDirectLink('1kYyuy1gjmosV2pa8-Ccx7y3xyizDfgKq'),
    },
    {
        id: 'irshad-audio-25',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 25',
        type: 'audio',
        url: getDirectLink('15cuPap-F8xs8GJ_qMjzLKYKEFck-HBdT'),
    },
    {
        id: 'irshad-audio-26',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 26',
        type: 'audio',
        url: getDirectLink('1s8pR1lcpDUI_9EIbRZukcS38L8a_L7a8'),
    },
    {
        id: 'irshad-audio-27',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 27',
        type: 'audio',
        url: getDirectLink('1rBf-BMQiALGEufm58NdhFzOJBkIpjXV9'),
    },
    {
        id: 'irshad-audio-28',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 28',
        type: 'audio',
        url: getDirectLink('1_unH0Hbef8r2sDvHG964EiYWThVAauDx'),
    },
    {
        id: 'irshad-audio-29',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 29',
        type: 'audio',
        url: getDirectLink('15Ho-tPUTJmKzczRTMiQOW7Itc3ifEK2z'),
    },
    {
        id: 'irshad-audio-30',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 30',
        type: 'audio',
        url: getDirectLink('1cEW_YIWvxY4F4oA1W0yCsMpRf6jGGI5C'),
    },
    {
        id: 'irshad-audio-31',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 31',
        type: 'audio',
        url: getDirectLink('1Nwk6-Ul9WKOrgcVHov0ycdpybyura05H'),
    },
    {
        id: 'irshad-audio-32',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 32',
        type: 'audio',
        url: getDirectLink('1tIi7N4RDRrpLHjtIF-ZxhRDlO5MkIzY6'),
    },
    {
        id: 'irshad-audio-33',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 33',
        type: 'audio',
        url: getDirectLink('1OC7sXEImck7nfncZqqWJRlT0bVr4d6e3'),
    },
    {
        id: 'irshad-audio-34',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 34',
        type: 'audio',
        url: getDirectLink('12ZUx4zGVjZ-6JoeZluJttBOwYWTKpv4C'),
    },
    {
        id: 'irshad-audio-35',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 35',
        type: 'audio',
        url: getDirectLink('1UrUnUCWkgjVc794moLhxVsdHaSKQ0UHJ'),
    },
    {
        id: 'irshad-audio-36',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 36',
        type: 'audio',
        url: getDirectLink('1eDlyPw6MPctbKBBaENA2vQH1o9Pc3i95'),
    },
    {
        id: 'irshad-audio-37',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 37',
        type: 'audio',
        url: getDirectLink('1xa84DMgsy3_-hAPutLoaBKXRgiPOhZkA'),
    },
    {
        id: 'irshad-audio-38',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 38',
        type: 'audio',
        url: getDirectLink('1ZNQVRliBJujWUgzwj_oWiLC0ze3ZqYef'),
    },
    {
        id: 'irshad-audio-39',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 39',
        type: 'audio',
        url: getDirectLink('1KjrR8CyhKvx4S729G0pS8vXBjkAoG9jA'),
    },
    {
        id: 'irshad-audio-40',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 40',
        type: 'audio',
        url: getDirectLink('1_S8fzKf_Rt09DZ8wR6Rp1oAoRQGFYJcn'),
    },
    {
        id: 'irshad-audio-41',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 41',
        type: 'audio',
        url: getDirectLink('1Tp4ImBJmZm8Ahjj_NdJ1G7DcbgxXCToX'),
    },
    {
        id: 'irshad-audio-42',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 42',
        type: 'audio',
        url: getDirectLink('1cN6s4Ofbqba4DpaxFH5XUppO0iOrZDr8'),
    },
    {
        id: 'irshad-audio-43',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 43',
        type: 'audio',
        url: getDirectLink('1KRuCf6VCTozqXucyMS2euCYJu6ts1x8W'),
    },
    {
        id: 'irshad-audio-44',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 44',
        type: 'audio',
        url: getDirectLink('1KRuCf6VCTozqXucyMS2euCYJu6ts1x8W'),
    },
    {
        id: 'irshad-audio-45',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 45',
        type: 'audio',
        url: getDirectLink('1Sne0IzygxymKRcGx9rt26ut_euu8Sna4'),
    },
    {
        id: 'irshad-audio-46',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 46',
        type: 'audio',
        url: getDirectLink('1y5P9z5ihU0-KRFCgBOyZRdf0TmfmBEp7'),
    },
    {
        id: 'irshad-audio-47',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 47',
        type: 'audio',
        url: getDirectLink('1c6vtrhi6pE1n63QKSbc8QWiNnEZzYHbJ'),
    },
    {
        id: 'irshad-audio-48',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 48',
        type: 'audio',
        url: getDirectLink('1GmSdHDlz2028oLGLsLCP7VacNbTcvgEZ'),
    },
    {
        id: 'irshad-audio-49',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 49',
        type: 'audio',
        url: getDirectLink('1ciQQ4AKUjFiE16kN_05vntWECQC-_sY-'),
    },
    {
        id: 'irshad-audio-50',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 50',
        type: 'audio',
        url: getDirectLink('1z25cPojkvCZoybe80v-bFbfNADpQB1RM'),
    },
    {
        id: 'irshad-audio-51',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 51',
        type: 'audio',
        url: getDirectLink('1b4SyFy3UB55x0EbEKg770giZYL5Rt9NF'),
    },
    {
        id: 'irshad-audio-52',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 52',
        type: 'audio',
        url: getDirectLink('1AdPWtc4j8q2nT42VqMXbjLAb1nrwx7Bk'),
    },
    {
        id: 'irshad-audio-53',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 53',
        type: 'audio',
        url: getDirectLink('1GQpNhkkwu7ESpWcYsiaFMfWth_fAM1o8'),
    },
    {
        id: 'irshad-audio-54',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 54',
        type: 'audio',
        url: getDirectLink('1fdVmFUwy3Zm-bF7TGHk4y61p0pbXHJv1'),
    },
    {
        id: 'irshad-audio-55',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 55',
        type: 'audio',
        url: getDirectLink('122TqXlxYb4g0nNJOcq_xCp6NTiuop8_F'),
    },
    {
        id: 'irshad-audio-56',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 56',
        type: 'audio',
        url: getDirectLink('1QSYgsT5FvmqL1-GPp_0jeRdzGepfLZ5v'),
    },
    {
        id: 'irshad-audio-57',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 57',
        type: 'audio',
        url: getDirectLink('1L44kqaZrHUPf6Dxci4wUO9JcISGi_FEx'),
    },
    {
        id: 'irshad-audio-58',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 58',
        type: 'audio',
        url: getDirectLink('12VaQZDMKrtQVtlSiPKfsvE3lOvqAyEGA'),
    },
    {
        id: 'irshad-audio-59',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 59',
        type: 'audio',
        url: getDirectLink('1zxoNoauVZ_6z4L7xETpL96OwWw9vniJJ'),
    },
    {
        id: 'irshad-audio-60',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 60',
        type: 'audio',
        url: getDirectLink('18HEUN62VHeT5lWgPj8iXLcS0QkGmp6tr'),
    },
    {
        id: 'irshad-audio-61',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 61',
        type: 'audio',
        url: getDirectLink('1aWtAc1honx6xMqaLmCLQxsIQQvDm7oaw'),
    },
    {
        id: 'irshad-audio-62',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 62',
        type: 'audio',
        url: getDirectLink('1iUWoLO0y6cuOwJPpS2-bQ5-rsShWgXpO'),
    },
    {
        id: 'irshad-audio-63',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 63',
        type: 'audio',
        url: getDirectLink('1_FNrwa4kt_giWqRlMnfHBYhENifX3Os0'),
    },
    {
        id: 'irshad-audio-64',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 64',
        type: 'audio',
        url: getDirectLink('1TONRNvMsYCpz5yaoRs2JcVAjo9i2E3jW'),
    },
    {
        id: 'irshad-audio-65',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 65',
        type: 'audio',
        url: getDirectLink('1Z8jdCm8_9HFWYx8ovR_ZP5r7VzdxUh1R'),
    },
    {
        id: 'irshad-audio-66',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 66',
        type: 'audio',
        url: getDirectLink('1sszKHeDWb1V5Dod6dqZb4aoUy0nmsM_O'),
    },
    {
        id: 'irshad-audio-67',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 67',
        type: 'audio',
        url: getDirectLink('1EYYpvX_WvGp1q5jmAsIfPK29BarIiJyU'),
    },
    {
        id: 'irshad-audio-68',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 68',
        type: 'audio',
        url: getDirectLink('10XiWGAobgiA9wU7ASH5e_HANdNLrfecE'),
    },
    {
        id: 'irshad-audio-69',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 69',
        type: 'audio',
        url: getDirectLink('1c5ATTPYKoEbYYd7EeomFWyb34S954VU7'),
    },
    {
        id: 'irshad-audio-70',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 70',
        type: 'audio',
        url: getDirectLink('1y-pHSkeO0jB4scKUv5aulpw7DsP39wYq'),
    },
    {
        id: 'irshad-audio-71',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 71',
        type: 'audio',
        url: getDirectLink('1FIzH2PiwIzoLGXmTNhm1Skn9by9NdPdu'),
    },
    {
        id: 'irshad-audio-72',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 72',
        type: 'audio',
        url: getDirectLink('1AzhK-Upw990aBuY0GasMHig8B-o3E3Tt'),
    },
    {
        id: 'irshad-audio-73',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 73',
        type: 'audio',
        url: getDirectLink('1yfj-_IZj-PVxI7pHIssOpiKxoYZ4FeMC'),
    },
    {
        id: 'irshad-audio-74',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 74',
        type: 'audio',
        url: getDirectLink('1G_HgDQonb8tjD_FKmDt-bmMrT7XrCoJA'),
    },
    {
        id: 'irshad-audio-75',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 75',
        type: 'audio',
        url: getDirectLink('1a4S7bT6dTeU7ouCOfSZA5lYcPrKSBRam'),
    },
    {
        id: 'irshad-audio-76',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 76',
        type: 'audio',
        url: getDirectLink('17Sphh5yumB6g1iM-JvHgNTpX89M2H6vk'),
    },
    {
        id: 'irshad-audio-77',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 77',
        type: 'audio',
        url: getDirectLink('1Xh9VF1jufcB70FYqUqEgsDe2x-73eV_C'),
    },
    {
        id: 'irshad-audio-78',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 78',
        type: 'audio',
        url: getDirectLink('1alTD8i9sK5EO1aWLSrKPKlyjpjSElrd_'),
    },
    {
        id: 'irshad-audio-79',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 79',
        type: 'audio',
        url: getDirectLink('18YI6V7j9Cl1oNOOPWu5BhTW_aolGliy4'),
    },
    {
        id: 'irshad-audio-80',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 80',
        type: 'audio',
        url: getDirectLink('1rSW_2YGE4znic9W7DqxfmgD0rmcRa7DS'),
    },
    {
        id: 'irshad-audio-81',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 81',
        type: 'audio',
        url: getDirectLink('1CIPo5tt77SiBTTuQqvkQbeSbGsN3Fskv'),
    },
    {
        id: 'irshad-audio-82',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 82',
        type: 'audio',
        url: getDirectLink('1A0Es31M791ReB7eFZkb27v936DxD4VVE'),
    },
    {
        id: 'irshad-audio-83',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 83',
        type: 'audio',
        url: getDirectLink('1rqIwdyZMXYF8rTgnFYBok76gkXA649b7'),
    },
    {
        id: 'irshad-audio-84',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 84',
        type: 'audio',
        url: getDirectLink('1XdlLfPUsyn1FX5rJrfR6R_HnrlmwYVLm'),
    },
    {
        id: 'irshad-audio-85',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 85',
        type: 'audio',
        url: getDirectLink('1CBEZjO27hDzfgueS6xLQPVXtq-wt1U-G'),
    },
    {
        id: 'irshad-audio-86',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 86',
        type: 'audio',
        url: getDirectLink('1JVYI3SqxFPTLMmhOI1RQLeRohZJY3VAo'),
    },
    {
        id: 'irshad-audio-87',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 87',
        type: 'audio',
        url: getDirectLink('1mzRiSKjc8Ew7wwctcFNf7rz5gzn_OM3n'),
    },
    {
        id: 'irshad-audio-88',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 88',
        type: 'audio',
        url: getDirectLink('1nm9EKPbX18CUPphhcbrQovemqEbkS5kC'),
    },
    {
        id: 'irshad-audio-89',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 89',
        type: 'audio',
        url: getDirectLink('1D5e90IKDyTTbi7FGYOefhokpaMPVfCRR'),
    },
    {
        id: 'irshad-audio-90',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 90',
        type: 'audio',
        url: getDirectLink('1Nq-RwVwGsAhOtdQmjeUN8YQTrM4LS4fC'),
    },
    {
        id: 'irshad-audio-91',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 91',
        type: 'audio',
        url: getDirectLink('1t0s7suBuoWE-RY0oyONO9WtnCbQUZZ4b'),
    },
    {
        id: 'irshad-audio-92',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 92',
        type: 'audio',
        url: getDirectLink('13nIdo9xlDatSWtVDMhetosGtP6TbetAq'),
    },
    {
        id: 'irshad-audio-93',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 93',
        type: 'audio',
        url: getDirectLink('1ubG6a2GB8_ZMXki3H7dw40VTtOEmNCPA'),
    },
    {
        id: 'irshad-audio-94',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 94',
        type: 'audio',
        url: getDirectLink('1RqS3aDPrYY_ycgRHIh6HGeNi9Ik6JfKl'),
    },
    {
        id: 'irshad-audio-95',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 95',
        type: 'audio',
        url: getDirectLink('1NLpFdgqigiBhRWDJXGx4r-Q97IbdxuXJ'),
    },
    {
        id: 'irshad-audio-96',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 96',
        type: 'audio',
        url: getDirectLink('1ArBc55G_ygvKGG-1foZlpWOX7rn27HJ6'),
    },
    {
        id: 'irshad-audio-97',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 97',
        type: 'audio',
        url: getDirectLink('1JhuQq0uYnG7gCG0SidA9_ZV9R3UT4dPy'),
    },
    {
        id: 'irshad-audio-98',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 98',
        type: 'audio',
        url: getDirectLink('18rhVzLfOGOSj2ttHnGakuQANFClqDiSo'),
    },
    {
        id: 'irshad-audio-99',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 99',
        type: 'audio',
        url: getDirectLink('1k4bTBweb4y2DW_RF6NZ1nP3vjwMrxvTC'),
    },
    {
        id: 'irshad-audio-100',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 100',
        type: 'audio',
        url: getDirectLink('14f0hFnpRHs2XNAFA3qmsFZkB6-w3QzRQ'),
    },
    {
        id: 'irshad-audio-101',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 101',
        type: 'audio',
        url: getDirectLink('1CgMFgopv3RM-kVduIYBMyM1i1bXfeKsO'),
    },
    {
        id: 'irshad-audio-102',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 102',
        type: 'audio',
        url: getDirectLink('1iyYYhmMlcbAtTEWDunUBcKN484oiELIn'),
    },
    {
        id: 'irshad-audio-103',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 103',
        type: 'audio',
        url: getDirectLink('1MFMTNgfjOD1W7k_3KMQm026TeMbHvoPm'),
    },
    {
        id: 'irshad-audio-104',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 104',
        type: 'audio',
        url: getDirectLink('1c6SmoSo2dw4afK2Ck2866BcnUN_iNum7'),
    },
    {
        id: 'irshad-audio-105',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 105',
        type: 'audio',
        url: getDirectLink('1MMXxBfWTmWKbD0AVh91lbTfDK1qIZnVd'),
    },
    {
        id: 'irshad-audio-106',
        name: 'الإرشاد إلى صحيح الاعتقاد ደርስ 106',
        type: 'audio',
        url: getDirectLink('1EvhRObhK0uFfX2bazuVZhlKVqOi1-8GR'),
    },
];

export const CATEGORIES: Category[] = [
    {
        id: 'hamuwiya',
        title: 'الحموية لابን تيمية',
        description: 'በ ሸህ አቡ ኒብራስ ሙስጠፋ የቀረበ',
        files: HAMUWIYA_FILES,
    },
    {
        id: 'irshad',
        title: 'الإرشاد إلى صحيح الاعتقاد',
        description: 'በ ሸህ አቡ ኒብራስ ሙስጠፋ የቀረበ',
        files: IRSHAD_FILES,
    },
    {
        id: 'future',
        title: 'ሌላ ደርስ (ምሳሌ)',
        description: 'ተጨማሪ ትምህርቶች እዚህ ይጨመራሉ',
        files: [],
    }
];

// For backward compatibility while refactoring other components
export const DRIVE_FILES = HAMUWIYA_FILES;
export const ALL_FILES = HAMUWIYA_FILES;
