import { DriveFile } from '../types';

// Helper to convert Google Drive view links to direct download links
const getDirectLink = (id: string) => `https://drive.google.com/uc?export=download&id=${id}`;

export const DRIVE_FILES: DriveFile[] = [
    {
        id: '1',
        name: 'ሙምቲዕ.pdf',
        type: 'pdf',
        url: getDirectLink('1bXCa2qS_Lq8NpCA1NDFArMU79D2kM1Pi'),
    },
    {
        id: '137',
        name: 'ሙምቲዕ ደርስ 137.mp3',
        type: 'audio',
        url: getDirectLink('1yl7g5X85VqjUhSKBdKhdAsBXLgHMcruD'),
    },
    {
        id: '138',
        name: 'ሙምቲዕ ደርስ 138.mp3',
        type: 'audio',
        url: getDirectLink('1wDFBHYdZCwSP1aRgnFAcw849Iaxv2Teq'),
    },
    {
        id: '139',
        name: 'ሙምቲዕ ደርስ 139.mp3',
        type: 'audio',
        url: getDirectLink('1ZmkGHM_3aCsitKFe30_SA50Qye0rvnJ9'),
    },
    {
        id: '140',
        name: 'ሙምቲዕ ደርስ 140.mp3',
        type: 'audio',
        url: getDirectLink('1f_nDKEzMv2pRa_SYEzVvVJnyDYXQh6V9'),
    },
    {
        id: '141',
        name: 'ሙምቲዕ ደርስ 141.mp3',
        type: 'audio',
        url: getDirectLink('1ia7bSMf7cy6HRRx8Tv1rKPCka5m2oxj2'),
    },
    {
        id: '142',
        name: 'ሙምቲዕ ደርስ 142.mp3',
        type: 'audio',
        url: getDirectLink('1pnHI5iHvaE4_c34IZEtoGOtpUO9udF9R'),
    },
    {
        id: '143',
        name: 'ሙምቲዕ ደርስ 143.mp3',
        type: 'audio',
        url: getDirectLink('1GsQbGdfeGwXUG7TgIpuClJQUTrrCCGPJ'),
    },
    {
        id: '144',
        name: 'ሙምቲዕ ደርስ 144.mp3',
        type: 'audio',
        url: getDirectLink('1KqaGmjpNHCGYF3VykOGrXoN_12X6bl5I'),
    },
    {
        id: '145',
        name: 'ሙምቲዕ ደርስ 145.mp3',
        type: 'audio',
        url: getDirectLink('10rfXnMIENaAzn2tkuNl-j7VXcyoKJQb6'),
    },
    {
        id: '146',
        name: 'ሙምቲዕ ደርስ 146.mp3',
        type: 'audio',
        url: getDirectLink('1Rts0M1_otBVqF_unQHqbI6vQKfyIdYH-'),
    },
    {
        id: '147',
        name: 'ሙምቲዕ ደርስ 147.mp3',
        type: 'audio',
        url: getDirectLink('14LK9fhkSvWsY8zBs0XSBAhM6-lzgIThZ'),
    },
    {
        id: '148',
        name: 'ሙምቲዕ ደርስ 148.mp3',
        type: 'audio',
        url: getDirectLink('1XcnkJyDb3PhtOGxnArA6xVPTwm3IboW7'),
    },
    {
        id: '149',
        name: 'ሙምቲዕ ደርስ 149.mp3',
        type: 'audio',
        url: getDirectLink('1OUK3GflSDjVOtDGNnHu7L3svfsTF_kgz'),
    },
    {
        id: '150',
        name: 'ሙምቲዕ ደርስ 150.mp3',
        type: 'audio',
        url: getDirectLink('1I-LFIGx1TnWGwvkj-eKe6soAfIrb76KN'),
    },
    {
        id: '151',
        name: 'ሙምቲዕ ደርስ 151.mp3',
        type: 'audio',
        url: getDirectLink('1Xf-MvSmekWIa-nqzGAvc-K_QcyNhm5-3'),
    },
    {
        id: '152',
        name: 'ሙምቲዕ ደርስ 152.mp3',
        type: 'audio',
        url: getDirectLink('1F_Sgs8ciCTAjCIw-ktvTliZs0zrnh_v7'),
    },
    {
        id: '153',
        name: 'ሙምቲዕ ደርስ 153.mp3',
        type: 'audio',
        url: getDirectLink('11oRBOPLhEYOAv-RJJUrvAXLrn4hX3bPR'),
    },
    {
        id: '154',
        name: 'ሙምቲዕ ደርስ 154.mp3',
        type: 'audio',
        url: getDirectLink('1NnLDAw5U4fVk86I-Bv02WAlV0nDvM-UC'),
    },
    {
        id: '155',
        name: 'ሙምቲዕ ደርስ 155.mp3',
        type: 'audio',
        url: getDirectLink('1Qr9Vzy230yeq4NguTMoy0k3CJ76BFwPh'),
    },
    {
        id: '156',
        name: 'ሙምቲዕ ደርስ 156.mp3',
        type: 'audio',
        url: getDirectLink('1xkDRQoLWUMdMauk2rOkSAAR87BhVZxOO'),
    },
    {
        id: '157',
        name: 'ሙምቲዕ ደርስ 157.mp3',
        type: 'audio',
        url: getDirectLink('1o3s5FmJP2Vgcvvm7InAYFZ8EYCKjPJ8D'),
    },
    {
        id: '158',
        name: 'ሙምቲዕ ደርስ 158.mp3',
        type: 'audio',
        url: getDirectLink('1dss57EIHaec9rm3GfwpwOnwuEV5JVucz'),
    },
    {
        id: '159',
        name: 'ሙምቲዕ ደርስ 159.mp3',
        type: 'audio',
        url: getDirectLink('1MRa59EsB3gaoks-JSTF6SAEs5KlznsKh'),
    },
    {
        id: '160',
        name: 'ሙምቲዕ ደርስ 160.mp3',
        type: 'audio',
        url: getDirectLink('1Y1XLGKyfGX21hGnBzCuCU2aGDCJwPeiD'),
    },
    {
        id: '161',
        name: 'ሙምቲዕ ደርስ 161.mp3',
        type: 'audio',
        url: getDirectLink('11kCob5cMfDjaRsLXjlSbwFaGdmN-MsZ_'),
    },
    {
        id: '162',
        name: 'ሙምቲዕ ደርስ 162.mp3',
        type: 'audio',
        url: getDirectLink('1c7we8LMm5DkjJGvzrAZNWI2KJkOYPcf-'),
    },
    {
        id: '163',
        name: 'ሙምቲዕ ደርስ 163.mp3',
        type: 'audio',
        url: getDirectLink('1MkWhbBUb6KDHBMRwj6Q0uqNdZuiGcs9Y'),
    },
    {
        id: '164',
        name: 'ሙምቲዕ ደርስ 164.mp3',
        type: 'audio',
        url: getDirectLink('1se1xTBrJyMst1hgCndsMOo7m9wQBoWju'),
    },
    {
        id: '165',
        name: 'ሙምቲዕ ደርስ 165.mp3',
        type: 'audio',
        url: getDirectLink('17iBt8DebZWNQA4ntvF5tB1y0ixORGHfU'),
    },
    {
        id: '166',
        name: 'ሙምቲዕ ደርስ 166.mp3',
        type: 'audio',
        url: getDirectLink('1Qi0LRB-OxgKFaoXI61GyrUfU_rXi2jzv'),
    },
    {
        id: '167',
        name: 'ሙምቲዕ ደርስ 167.mp3',
        type: 'audio',
        url: getDirectLink('1zK8w44fY27ajNeEMIMQmWxA9xiPqdKdc'),
    },
    {
        id: '168',
        name: 'ሙምቲዕ ደርስ 168.mp3',
        type: 'audio',
        url: getDirectLink('1F4dfBHSv0WtiV-XM8PCQkv8sGmvoeyb0'),
    },
    {
        id: '169',
        name: 'ሙምቲዕ ደርስ 169.mp3',
        type: 'audio',
        url: getDirectLink('1NskgOiBQWvpo6NLijtMgCkYNSuRdBR8R'),
    },
    {
        id: '170',
        name: 'ሙምቲዕ ደርስ 170.mp3',
        type: 'audio',
        url: getDirectLink('1Kuu1cOC7pqr55aTrZnQJOLz1Ho_dW-8p'),
    },
    {
        id: '171',
        name: 'ሙምቲዕ ደርስ 171.mp3',
        type: 'audio',
        url: getDirectLink('11rxdZPqr2GwjfauLlgeNEExgFVV1dX0n'),
    },
    {
        id: '172',
        name: 'ሙምቲዕ ደርስ 172.mp3',
        type: 'audio',
        url: getDirectLink('1-iBTknlBLLjPSneVryljnCbGJBe0Osyx'),
    },
    {
        id: '173',
        name: 'ሙምቲዕ ደርስ 173.mp3',
        type: 'audio',
        url: getDirectLink('13UGm2_EJnHIwDZc5RUjbh6_2RXlfj3k7'),
    },
    {
        id: '174',
        name: 'ሙምቲዕ ደርስ 174.mp3',
        type: 'audio',
        url: getDirectLink('1Kk2XUtjkMEFfPw_ePAsRZa9Jo22MYc9t'),
    },
    {
        id: '175A',
        name: 'ሙምቲዕ ደርስ 175A.mp3',
        type: 'audio',
        url: getDirectLink('1LqAi9vZ9RypU-eI3IHSPtR-wD_6L2hNo'),
    },
    {
        id: '175B',
        name: 'ሙምቲዕ ደርስ 175B.mp3',
        type: 'audio',
        url: getDirectLink('1T1DM6KgIvcdjxvQREBtGLUXISK_z6xz9'),
    },
    {
        id: '176',
        name: 'ሙምቲዕ ደርስ 176.mp3',
        type: 'audio',
        url: getDirectLink('1WB8kSF3yX3wujDvllGdZtULcqzcSdinO'),
    },
    {
        id: '177',
        name: 'ሙምቲዕ ደርስ 177.mp3',
        type: 'audio',
        url: getDirectLink('1oLrEAOBTNWZJpciN2hVWpVzanvhNA481'),
    },
    {
        id: '178',
        name: 'ሙምቲዕ ደርስ 178.mp3',
        type: 'audio',
        url: getDirectLink('1SvgTywQr5ZvDFxKJhAA6j53WDY6QFXsA'),
    },
    {
        id: '179',
        name: 'ሙምቲዕ ደርስ 179.mp3',
        type: 'audio',
        url: getDirectLink('1hZGeCbQdYESdJYRZV9ind-1p04_Ii0Ou'),
    },
    {
        id: '180',
        name: 'ሙምቲዕ ደርስ 180.mp3',
        type: 'audio',
        url: getDirectLink('1heLlI_jLZa30dKZ5UKQKefs-YJhKDkaW'),
    },
    {
        id: '181',
        name: 'ሙምቲዕ ደርስ 181.mp3',
        type: 'audio',
        url: getDirectLink('11n736sgZ6odIZpTgEQsg0VFwKFClTfX6'),
    },
    {
        id: '182',
        name: 'ሙምቲዕ ደርስ 182.mp3',
        type: 'audio',
        url: getDirectLink('19WbaRKAHg9EdAVsa-tWTHYdzdVgamXKK'),
    },
    {
        id: '183',
        name: 'ሙምቲዕ ደርስ 183.mp3',
        type: 'audio',
        url: getDirectLink('1yEqb8VN2o2tWyvBfIck0t9fRQsNeQAwb'),
    },
    {
        id: '184',
        name: 'ሙምቲዕ ደርስ 184.mp3',
        type: 'audio',
        url: getDirectLink('18s_mzPI-1KrtYP7O-dXoOYbF4O9wBPBu'),
    },
    {
        id: '185',
        name: 'ሙምቲዕ ደርስ 185.mp3',
        type: 'audio',
        url: getDirectLink('1G78FwtmL7e5DSIMejZclhmuw0OtLjUcR'),
    },
    {
        id: '186',
        name: 'ሙምቲዕ ደርስ 186.mp3',
        type: 'audio',
        url: getDirectLink('1ojktWdaR7T9Vn2YqQoycCZX_WFayXULP'),
    },
    {
        id: '187',
        name: 'ሙምቲዕ ደርስ 187.mp3',
        type: 'audio',
        url: getDirectLink('1-ob38RDKd9tNEelkaDVKyOcUQeWTpISy'),
    },
    {
        id: '188',
        name: 'ሙምቲዕ ደርስ 188.mp3',
        type: 'audio',
        url: getDirectLink('1ofVUiGcBwxgeJmbNQk3wI7_P0GuqQfyW'),
    },
    {
        id: '189',
        name: 'ሙምቲዕ ደርስ 189.mp3',
        type: 'audio',
        url: getDirectLink('18Ga-xT73KbXu-u1Qu9OfsCNZ0ggCA4fE'),
    },
    {
        id: '190',
        name: 'ሙምቲዕ ደርስ 190.mp3',
        type: 'audio',
        url: getDirectLink('1i3Bq5CnAz0pAfvSUmglWcwxT2gM-eIwI'),
    },
    {
        id: '191',
        name: 'ሙምቲዕ ደርስ 191.mp3',
        type: 'audio',
        url: getDirectLink('114PDedUaquN1Q0fV9JLqYIkPPBm3lEMX'),
    },
    {
        id: '192',
        name: 'ሙምቲዕ ደርስ 192.mp3',
        type: 'audio',
        url: getDirectLink('192sYpR-FUIK9Xqt4fmAEBi6pJxzLFS3K'),
    },
    {
        id: '193',
        name: 'ሙምቲዕ ደርስ 193.mp3',
        type: 'audio',
        url: getDirectLink('1Uk6Qx6BVNKXcdh9eWB47hf8M2DQpGTZb'),
    },
    {
        id: '194',
        name: 'ሙምቲዕ ደርስ 194.mp3',
        type: 'audio',
        url: getDirectLink('1JJafDkZDwZjfsnv06nyU6rpXRo-v1VX_'),
    },
    {
        id: '195',
        name: 'ሙምቲዕ ደርስ 195.mp3',
        type: 'audio',
        url: getDirectLink('1VEomKEQYRdLu5MpYaPvuZLuPCjJPS1WP'),
    },
    {
        id: '196',
        name: 'ሙምቲዕ ደርስ 196.mp3',
        type: 'audio',
        url: getDirectLink('1yyZEueUIn2DqbSEDP9NgF4TPPjf07vTp'),
    },
    {
        id: '197',
        name: 'ሙምቲዕ ደርስ 197.mp3',
        type: 'audio',
        url: getDirectLink('1hjBp4zCevSJf0cuA0jmMBCc32ZhRY-Dr'),
    },
    {
        id: '198',
        name: 'ሙምቲዕ ደርስ 198.mp3',
        type: 'audio',
        url: getDirectLink('1WTqyDuAaSRyqcRisjTIgMB1ZKUh1MsQf'),
    },
    {
        id: '199',
        name: 'ሙምቲዕ ደርስ 199.mp3',
        type: 'audio',
        url: getDirectLink('1_3HNGKq_JtR8Q4SDMfA2w_40Xh1n6UEE'),
    },
    {
        id: '200',
        name: 'ሙምቲዕ ደርስ 200.mp3',
        type: 'audio',
        url: getDirectLink('1x5hZKhMo84CW_2MZMYKfQOpeHwbWaEy9'),
    },
    {
        id: '201',
        name: 'ሙምቲዕ ደርስ 201.mp3',
        type: 'audio',
        url: getDirectLink('1M7AgyJXvaSGahmaKef6G5jCeQflwP-Hl'),
    },
    {
        id: '202',
        name: 'ሙምቲዕ ደርስ 202.mp3',
        type: 'audio',
        url: getDirectLink('1xN4-a83isTRRbJorm1iml6qGQhlU3vuC'),
    }
];

